// 화면 문구와 이력 데이터 (한국어·영어)
const TEXT = {
  ko: {
    brand: "이우석 스테이",
    pill: "승인 대기",
    status: "풀타임 개발자 1명이 가예약되어 있습니다",
    name: "이우석 · 풀스택 엔지니어 · 위홈 기술·운영 총괄",
    pdf: "PDF 이력서(영문)",
    tagline: "AI 코딩 에이전트로 만들고, 모든 변경은 직접 검증합니다.",
    where: "경기 고양시 · GMT+9 · 출근·재택 모두 가능",
    h_about: "숙소 소개",
    about: "숙소 8,000곳 이상의 공유숙박 플랫폼 위홈에서 기술·운영 총괄로 웹·백엔드·AWS를 이끌고, iOS·Android 앱 수정·개선은 입사 후 모두 직접 하고 있습니다. 예약부터 결제·정산까지 책임집니다. 코드는 에이전트가 쓰고 경계는 코드로 정합니다.",
    h_reviews: "이용 후기",
    reviews_note: "근거 보기를 누르면 어떻게 쟀는지 나옵니다",
    h_amen: "편의시설",
    h_stays: "이전 숙박",
    h_gallery: "숙소 갤러리",
    gallery_note: "호스트가 직접 디자인하고 만든 예약 사이트",
    repause: "리포즈(repause.co.kr): 프라이빗 풀빌라 예약 사이트. 외주로 디자인부터 결제·배포까지 혼자 만들었습니다. 일반·제휴 예약, 토스페이먼츠, 쿠폰, 보증금 분할 결제, 관리자. Next.js · TypeScript · Tailwind · Prisma.",
    h_rules: "하우스 룰",
    h_where: "위치와 시간대",
    rate: "요금 협의",
    rate_unit: "/ 첫 통화에서",
    f_checkin: "체크인 희망일",
    f_type: "숙박 형태",
    f_mode: "근무 방식",
    f_team: "팀·회사 이름 (선택)",
    cta: "예약 요청",
    cta_short: "예약 요청",
    no_charge: "아직 아무것도 청구되지 않습니다",
    s_dev: "개발자 1명 × 장기 숙박",
    s_agent: "AI 에이전트 운영 노하우",
    s_cancel: "수습 기간 중 취소",
    s_free: "포함",
    s_total: "합계",
    s_total_v: "첫 통화에서 협의",
    err_date: "체크인 희망일을 골라 주세요",
    conf_title: "예약 요청이 준비됐습니다",
    conf_body: "아래 버튼으로 메일을 보내 주시면 통화 일정을 잡겠습니다. 실제 결제는 없습니다.",
    c_checkin: "체크인", c_type: "숙박 형태", c_mode: "근무 방식", c_team: "팀",
    send: "메일로 보내기",
    close: "닫기",
    mail_subject: "[예약 요청] 이우석 채용 문의",
    mail_from: "이 메일은 sinabro-wooseok.github.io 이력서 페이지에서 만들어졌습니다.",
    footer: "이 페이지는 실제 숙박 예약 사이트가 아니라 이우석의 이력서입니다. 국문 PDF 이력서는 메일로 요청해 주세요.",
    tz_seoul: "지금 서울은",
    tz_you: "당신의 시간대",
    tz_overlap: (h) => h > 0 ? `오전 9시~오후 6시 기준으로 업무 시간이 ${h}시간 겹칩니다.` : "업무 시간이 겹치지 않아 글로 하는 비동기 협업이 맞습니다.",
    tz_same: "같은 시간대입니다. 바로 통화할 수 있습니다.",
    all: "전체",
  },
  en: {
    brand: "Wooseok Stay",
    pill: "Pending",
    status: "A full-time engineer is on hold for your team",
    name: "Wooseok Lee · Full-stack engineer · Head of Technology & Operations, Wehome",
    pdf: "Resume PDF",
    tagline: "Builds with AI coding agents. Verifies every change himself.",
    where: "Goyang, Seoul area · GMT+9 · remote or on-site",
    h_about: "About this stay",
    about: "Head of Technology & Operations at Wehome, a Korean short-term rental marketplace with 8,000+ listings. I lead web, backend, AWS and native iOS/Android apps, from bookings to payments and settlement; every app change since I joined is mine. Agents do the typing; the boundaries live in code.",
    h_reviews: "Guest reviews",
    reviews_note: "tap “How measured” to see the evidence",
    h_amen: "Amenities",
    h_stays: "Previous stays",
    h_gallery: "Property gallery",
    gallery_note: "a booking site the host designed and built himself",
    repause: "Repause (repause.co.kr): a private pool villa booking site. Freelance, designed, built and deployed solo. Standard and partner booking, Toss Payments, coupons, split deposit, admin. Next.js · TypeScript · Tailwind · Prisma.",
    h_rules: "House rules",
    h_where: "Location & time zone",
    rate: "Rate on request",
    rate_unit: "/ discussed on the first call",
    f_checkin: "Preferred check-in",
    f_type: "Stay type",
    f_mode: "Work mode",
    f_team: "Team or company (optional)",
    cta: "Request to book",
    cta_short: "Request",
    no_charge: "You won't be charged anything",
    s_dev: "1 engineer × long stay",
    s_agent: "AI-agent workflow know-how",
    s_cancel: "Cancellation during probation",
    s_free: "included",
    s_total: "Total",
    s_total_v: "On the first call",
    err_date: "Please pick a check-in date",
    conf_title: "Your booking request is ready",
    conf_body: "Send it by email and I'll set up a call. Nothing is charged.",
    c_checkin: "Check-in", c_type: "Stay type", c_mode: "Work mode", c_team: "Team",
    send: "Send by email",
    close: "Close",
    mail_subject: "[Booking request] Hiring Wooseok Lee",
    mail_from: "Generated from the resume page at sinabro-wooseok.github.io.",
    footer: "This is not a real lodging site. It is Wooseok Lee's resume. The PDF version is linked at the top.",
    tz_seoul: "It's now in Seoul",
    tz_you: "Your time zone",
    tz_overlap: (h) => h > 0 ? `${h} hours of overlap on a 9-to-6 workday.` : "No overlapping work hours, so async, written collaboration fits best.",
    tz_same: "Same time zone. We can talk right away.",
    all: "All",
  },
};

// 첫 화면 핵심 숫자
const HERO_KPI = [
  { n: "279 → 0", ko: "Airbnb와 이중 예약될 수 있던 박수", en: "nights open to double booking vs Airbnb" },
  { n: "40.7s → 1.1s", ko: "가장 느린 관리자 화면", en: "slowest admin screen" },
  { n: "+52 / +62", ko: "3주간 iOS / Android 출시 빌드", en: "iOS / Android builds shipped in 3 weeks" },
];

const FEAT = [
  { k: "01", ko: ["직접 검증하는 호스트", "실서버 화면에서 확인하기 전에는 끝났다고 하지 않습니다."], en: ["A host who verifies", "Nothing is “done” until it is checked on the live screen."] },
  { k: "02", ko: ["공식 API가 없어도 연동", "Airbnb GraphQL, Agoda YCS, Channex, 투지아, 구글 호텔 피드."], en: ["Integrations without a public API", "Airbnb GraphQL, Agoda YCS, Channex, Tujia, Google Hotel feed."] },
  { k: "03", ko: ["디자인도 하는 개발자", "리포즈 예약 사이트를 디자인부터 배포까지 혼자 만들었습니다."], en: ["An engineer who designs", "Designed and shipped the Repause booking site solo."] },
];

const CATS = [
  { id: "int", ko: "연동", en: "Integrations" },
  { id: "perf", ko: "성능·인프라", en: "Perf & infra" },
  { id: "app", ko: "앱", en: "Mobile" },
  { id: "ai", ko: "AI·자동화", en: "AI & automation" },
  { id: "design", ko: "디자인", en: "Design" },
  { id: "sec", ko: "보안", en: "Security" },
];

const REVIEWS = [
  { c: "int", n: "953 → 264",
    ko: ["Airbnb에선 예약됐는데 위홈 달력은 열려 있던 날을 49곳 → 8곳으로, 손님이 예약할 수 있던 279박은 0박으로 줄였습니다. 동기화 버그 4개 수정.", "수정 전후 같은 기준(Airbnb 확정 예약 vs 위홈 달력)으로 전체 숙소를 대조했습니다."],
    en: ["Nights booked on Airbnb but still open on our calendar: 49 listings → 8, and guest-bookable nights 279 → 0. Four sync bugs fixed.", "Full comparison of Airbnb-confirmed bookings against our calendar, same rule before and after the fixes."] },
  { c: "int", n: "87 pages",
    ko: ["Airbnb 전체 스캔이 조용히 중간에 끊기던 문제. 첫 진단이 틀렸던 걸 재현으로 확인하고 진짜 원인을 찾아 완주로 복구했습니다.", "오진부터 정정까지 운영 기록에 남겼고, 같은 문제를 막는 회귀 테스트 66건을 추가했습니다."],
    en: ["Airbnb scans were silently stopping early. My first diagnosis was wrong; I reproduced it, found the real cause and restored full runs.", "The misdiagnosis and the correction are both in the ops log, and 66 regression tests now guard it."] },
  { c: "int", n: "76 × 30 min",
    ko: ["공동호스트 권한 대조를 4가지 상태 모델로 설계해 숙소 76곳을 30분마다 자동 점검합니다.", "Airbnb의 공동호스트 권한과 위홈 기록을 4가지 상태로 나눠 차이를 찾아냅니다."],
    en: ["Designed co-host permission reconciliation on a 4-state model; 76 listings are checked every 30 minutes.", "Airbnb co-host permissions and our records are sorted into four states, so every mismatch is visible."] },
  { c: "perf", n: "40.7s → 1.1s",
    ko: ["관리자 병목을 실측하고 고쳤습니다. 5.4 → 0.39초, 17 → 0.07초, 날짜 가용 확인 168 → 18ms.", "같은 화면·같은 데이터로 변경 전후 응답 시간을 쟀습니다. 한 시점의 측정값입니다."],
    en: ["Measured and fixed admin bottlenecks. Also 5.4s → 0.39s, 17s → 0.07s, availability check 168 → 18 ms.", "Same screen, same data, timed before and after the change. Single-point measurements."] },
  { c: "perf", n: "600 → 50",
    ko: ["헤드리스 브라우저 크롤러 팜을 WAF 규칙 4개로 막았습니다. 분당 요청 600 → 50, 5분 합계 5xx 오류 1,300 → 40.", "Cloudflare 트래픽 분석으로 패턴을 찾고, 규칙 적용 전후를 같은 지표로 비교했습니다."],
    en: ["Stopped a headless-browser crawler farm with 4 WAF rules: 600 → 50 req/min, 5xx errors 1,300 → 40 per 5 min.", "Found the pattern in Cloudflare analytics and compared the same metrics before and after."] },
  { c: "perf", n: "Go · SQLite",
    ko: ["Go와 SQLite로 친구 관계·타임라인·실시간 채팅(SSE) API를 만들어 공개했습니다. 연결이 끊겨도 놓친 메시지를 이어 받습니다.", "새 언어를 익히며 만든 예제입니다. 동시성 검사(-race)를 켠 테스트와 설계 판단을 README에 정리했습니다."],
    en: ["Built and open-sourced a small Go + SQLite social API: friendships, a cursor-paginated timeline and real-time chat over SSE that resumes after a disconnect.", "A learning project in a new language. Tests run with the race detector, and the design trade-offs are in the README."], link: "https://github.com/Sinabro-wooseok/go-sqlite-social" },
  { c: "perf", n: "FastAPI · BigQuery",
    ko: ["FastAPI로 외부 API 데이터를 모아 BigQuery에 적재하는 수집기를 만들어 공개했습니다. 세션 만료·요청 제한·일시 장애는 재시도로 넘기고, 빠진 줄이나 순위 역전은 저장 전에 막습니다.", "날짜 단위 파티션 교체라 몇 번 다시 돌려도 중복이 없고, 실패한 날만 다시 받으며, 수집이 조용히 멈추면 상태 확인이 실패를 알립니다. 테스트 18개."],
    en: ["Built and open-sourced a FastAPI collector that loads external API data into BigQuery. Session expiry, rate limits and transient errors are retried; missing rows and rank inversions are blocked before write.", "Day-partition replace loads make reruns idempotent, backfills resume from failed days only, and a health check fails when runs silently stop. 18 tests."], link: "https://github.com/Sinabro-wooseok/fastapi-resilient-collector" },
  { c: "ai", n: "RAG · leaks 0",
    ko: ["사내 문서 RAG 검색 예제를 만들어 공개했습니다. 권한 필터를 순위 매기기 전에 걸어 볼 수 없는 문서는 점수에도 안 나오고, 근거가 부족하면 답하지 않으며, 문서 속 지시문·링크·개인정보는 모델에 넘기기 전에 가립니다.", "질문 16개 평가에서 권한 누출 0, 거절 정확도 1.0. 첫 판은 0.75였고 고친 과정까지 README에 적었습니다. 운영 데이터가 아닌 설계 검증용 예제입니다."],
    en: ["Built and open-sourced an enterprise-docs RAG search example. ACLs filter before ranking so forbidden docs never show up in scores, answers are refused when evidence is thin, and injected instructions, links and personal data are masked before reaching the model.", "On a 16-question eval: 0 ACL leaks, refusal accuracy 1.0 (up from 0.75 in the first version; the fix is in the README). A design-validation example, not production data."], link: "https://github.com/Sinabro-wooseok/rag-guarded-search" },
  { c: "app", n: "+52 / +62",
    ko: ["입사 후 iOS·Android 앱의 수정·개선은 모두 제가 직접 했습니다. 약 3주 동안 iOS 빌드 69 → 121, Android 88 → 150을 연속 출시했습니다.", "홈 영상 앱 안 재생, 숙소 화면 스크롤 끊김 개선, 구글 로그인 오류·가격 필터 수정, 메시지 사진 10장 전송, 예약 후 평점 요청 등. 스토어 빌드 번호 기준이며 출시마다 Maestro 회귀 시나리오 8개로 점검했습니다."],
    en: ["Every iOS and Android app change since I joined is my own work. Shipped iOS builds 69 → 121 and Android 88 → 150 in about three weeks.", "In-app video playback, smoother stay pages, Google sign-in and price-filter fixes, 10-photo messages, an in-app rating prompt. Counted by store build numbers; every release ran 8 Maestro regression flows."] },
  { c: "ai", n: "57 · 39 · 31",
    ko: ["규칙 57개, 훅 39개, 스킬 31개로 코딩 에이전트를 운영합니다. 삭제·고객 발송·돈이 걸린 일은 사람이 승인해야 넘어갑니다.", "일부를 GitHub agent-guardrails 저장소에 공개했습니다."],
    en: ["I run coding agents with 57 rules, 39 hooks and 31 skills. Deletes, customer messages and money wait for a human.", "Part of it is open source in the agent-guardrails repository on GitHub."], link: "https://github.com/Sinabro-wooseok/agent-guardrails" },
  { c: "ai", n: "6 hook points",
    ko: ["에이전트 실행 흐름의 6개 지점(세션 시작·매 질문·도구 실행 전후·답변 종료·대화 압축 직전)에 훅을 걸어, 규칙을 프롬프트가 아니라 실행 단계에서 강제합니다.", "장기 기억(파일 하나에 사실 하나)과 지연 작업 대기열까지 한 장 구조도로 공개했습니다."],
    en: ["Hooks sit at 6 points of the agent loop (session start, every prompt, before and after each tool, the final answer, before compaction), so rules are enforced at runtime, not in the prompt.", "The one-page diagram also covers long-term memory (one fact per file) and the deferred-check queue."], link: "https://github.com/Sinabro-wooseok/agent-guardrails#how-the-whole-setup-is-wired" },
  { c: "ai", n: "81 tests",
    ko: ["광고비 상한을 넘으면 자동으로 멈추는 장치를 만들고, 플랫폼 전환 수와 실제 결제가 어긋나는 걸 찾아 입찰 확대를 멈췄습니다.", "광고 플랫폼의 전환 수를 실제 결제 데이터와 직접 대조했습니다. 장치에는 테스트 81개가 붙어 있습니다."],
    en: ["Built an ad-spend auto-pause guard and caught a conversion mismatch that stopped a bid scale-up.", "Compared platform-reported conversions with real payment data. The guard has 81 tests."] },
  { c: "ai", n: "89 hosts",
    ko: ["호스트용 AI 답장 초안을 전면 도입하기 전에 89명 대상 시범 운영과 진행·중단 기준부터 설계했습니다.", "도입 여부를 감이 아니라 미리 정한 기준으로 판단하도록 했습니다."],
    en: ["Before rolling out AI-drafted host replies, I designed an 89-host pilot with GO/NO-GO criteria.", "The rollout decision is made against criteria set in advance, not by feel."] },
  { c: "ai", n: "50%+",
    ko: ["더추모에서 Cursor·Claude를 실무에 도입해 퍼블리싱·기능 개발 기간을 절반 이상 줄였습니다.", "도입 전후 비슷한 작업의 개발 기간을 비교했습니다."],
    en: ["At The Choomo, brought Cursor + Claude into daily work and cut publishing and feature time by more than half.", "Compared delivery time for similar tasks before and after."] },
  { c: "design", n: "repause.co.kr",
    ko: ["프라이빗 풀빌라 예약 사이트를 디자인부터 결제·배포까지 혼자 만들었습니다.", "직접 들어가 보실 수 있습니다."],
    en: ["Designed and built a private pool villa booking site solo, from art direction to payments and deploy.", "It's live, so you can try it yourself."], link: "https://repause.co.kr" },
  { c: "sec", n: "Private", locked: true,
    ko: ["보안 사고 대응과 권한 분리 경험이 있습니다. 회사 보안상 자세한 내용은 면접에서 말씀드립니다.", "이 후기는 공개 페이지에서 일부러 가렸습니다."],
    en: ["Incident response and least-privilege work. Details stay private for my employer's sake; happy to walk through them in an interview.", "Hidden on purpose on this public page."] },
];

const AMEN = [
  { ko: "백엔드", en: "Backend", v: "PHP (CodeIgniter), MySQL, Python, Node.js, REST, cron/batch" },
  { ko: "프론트", en: "Frontend", v: "TypeScript, React, Next.js, Tailwind, Framer Motion, accessible UI" },
  { ko: "앱", en: "Mobile", v: "Swift (iOS), Java (Android), WebView hybrid, store releases, Maestro" },
  { ko: "클라우드", en: "Cloud & edge", v: "AWS (EC2, RDS, Bedrock, CloudWatch), Cloudflare WAF, Sentry, Elasticsearch" },
  { ko: "AI", en: "AI", v: "Claude Code, Claude API, MCP, AWS Bedrock, Cursor, Gemma, human-approval gates" },
  { ko: "외부 연동", en: "Integrations", v: "Airbnb GraphQL, Agoda YCS, Channex, Tujia, Booking iCal, 5 payment gateways" },
];

const STAYS = [
  { when: "2025.12 –", ko: ["위홈", "기술·운영 총괄, 풀스택 개발 리드", "PHP·JS 웹, MySQL, AWS, iOS·Android 앱(입사 후 앱 수정·개선 전부 직접). 외부 서비스 30여 개, 크론 229개. AWS Bedrock 생성형 AI 기능을 사람 최종 검수와 함께 운영."],
    en: ["Wehome", "Head of Technology & Operations, lead full-stack engineer", "PHP/JS web, MySQL, AWS, native iOS and Android (every app change since joining is mine). 30+ external services, 229 scheduled jobs. Generative AI on AWS Bedrock with human final review."] },
  { when: "2026.04 – 2026.09", ko: ["리포즈", "외주(크리오스), 디자인·개발 단독", "프라이빗 풀빌라 예약 사이트를 디자인부터 결제·배포까지 혼자 만들었습니다. Next.js·TypeScript·토스페이먼츠. 운영 중."],
    en: ["Repause", "Freelance (via Krios), solo designer and developer", "A private pool villa booking site, designed, built and deployed solo. Next.js, TypeScript, Toss Payments. Live."] },
  { when: "2025.05 – 2026.01", ko: ["더추모", "웹개발자·팀장(5명 팀), 웹사이트 단독 구축·운영", "AI 개발 도입으로 개발 기간 50% 이상 단축, 실시간 알림톡, 비개발자용 관리자 화면."],
    en: ["The Choomo", "Web developer & team lead (team of 5), built and ran the site alone", "AI-assisted development (50%+ faster), real-time KakaoTalk alerts, a self-serve admin UI."] },
  { when: "2023.01 – 2025.04", ko: ["프리랜서", "웹퍼블리셔", "업종이 다른 사이트의 반응형 재설계·접근성 마크업·오류 수정."],
    en: ["Freelance", "Web publisher", "Responsive rebuilds, accessible markup and debugging across industries."] },
  { when: "2024.09 – 2024.12", ko: ["에어패스", "AI 데이터", "장애인 접근성 AI 과제의 행동·음성 데이터 전처리·라벨링·검수."],
    en: ["Airpass", "AI data specialist", "Gesture and atypical-speech data for a government-funded accessibility AI."] },
  { when: "2017.03 – 2024.02", ko: ["리앤양", "웹개발자·단독 팀장(6명 팀), Cafe24 자사몰 7년", "입사 3개월 만에 팀장. UI, PG 결제, 회원등급·적립금·쿠폰, 모바일 결제 단계 축소."],
    en: ["LeeAndYang", "Web developer & sole team lead (team of 6), 7 years", "Team lead 3 months after joining. Storefront UI, PG payments, tiers, points, coupons, a shorter mobile checkout."] },
];

const RULES = {
  ko: ["코드는 에이전트가 써도, 돈·삭제·고객 발송은 사람이 승인합니다.", "실서버 화면에서 확인하기 전에는 “끝났다”고 하지 않습니다.", "진단이 틀렸으면 조용히 넘기지 않고 기록으로 정정합니다.", "근거 없는 숫자는 이 페이지에 싣지 않았습니다.", "경계는 프롬프트가 아니라 코드에 둡니다."],
  en: ["Agents may write the code; a person approves money, deletes and customer messages.", "Nothing is “done” until it is checked on the live screen.", "A wrong diagnosis gets corrected in writing, not quietly.", "Numbers without evidence stay off this page.", "Boundaries go in code, not in the prompt."],
};

const TYPES = { ko: ["정규직", "계약직", "프로젝트"], en: ["Full-time", "Contract", "Project"] };
const MODES = { ko: ["출근", "하이브리드", "재택"], en: ["On-site", "Hybrid", "Remote"] };
